name: VAdatapipeline

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
<<<<<<< HEAD
      - name: Run Python script
        run: python main.py
=======
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data pipeline
        env:
          MONGODB_URL: ${{secrets.MONGODB_url}}
        run: python main.py
      - name: Check for changes
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions'@github.com'
          git add .
          git diff --stagged --quiet || echo "changes=true" >> $GITHUB_ENV
      - name: Commit and push if changes
        if: env.changes == "true"
        run: |
          git commit -m "updated pipeline"
          git push
>>>>>>> da51cd8a7a5a14dfa3254091b37640087c754e62
